[package]

name = "freetype"
version = "0.1.0"
authors = ["The Servo Project Developers"]
documentation = "http://doc.servo.org/freetype/"

[lib]

name = "freetype"
crate-type = ["rlib"]

[dependencies]
libc = "*"
servo-freetype-sys = "4.0.2"
